cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('display/', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('Customer/', include('Customer.urls')),
    path('order/',include('order.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views
app_name = 'order'
urlpatterns = [
 path('checkout/', views.order_create, name='checkout'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from store.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart.html', {'cart': cart})

cart/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}
<section class="navbar main-menu">
    <div class="navbar-inner main-menu">				
        <a href="{% url 'index' %}" class="logo pull-left"><img src="{% static 'themes/images/logo.png' %}" class="site_logo" alt=""></a>
        <nav id="menu" class="pull-right">
            <ul>
                {% for category in category %}
                <li><a href="./products.html">{{category.name}}</a></li>
                {% endfor %}
            </ul>
        </nav>
    </div>
</section>
{% endblock navbar %}

{% block main-content %}
<section class="header_text sub">
    <img class="pageBanner" src="{% static 'themes/images/pageBanner.png' %}" alt="New products" >
        <h4><span>Shopping Cart</span></h4>
    </section>
    <section class="main-content">				
        <div class="row">
            <div class="span9">					
                <h4 class="title"><span class="text"><strong>Your</strong> Cart</span></h4>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Remove</th>
                            <th>Image</th>
                            <th>Product Name</th>
                            <th>Quantity</th>
                            <th>Unit Price</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart %}
                            {% with product=item.product%}
                            <tr>
                                <td><form action="{% url 'cart:cart_remove' product.id %}" method="POST">
                                    {% csrf_token %}
                                    <button class="btn btn-inverse" type="submit">remove</button>
                                </form></td>
                                <td><a href="product_detail.html"><img alt="" src="{{product.image.url}}" style="height: 150px;"></a></td>
                                <td>{{product.name}}</td>
                                <td>{{item.quantity}}</td>
                                <td>${{item.price}}</td>
                                <td>${{item.total_price}}</td>
                            </tr>			
                            {% endwith %}
                        {% endfor %}
                          
                       
                    </tbody>
                </table>
                <h4>What would you like to do next?</h4>
                <p>Choose if you have a discount code or reward points you want to use or would like to estimate your delivery cost.</p>
                <label class="radio">
                    <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked="">
                    Use Coupon Code
                </label>
                <label class="radio">
                    <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
                    Estimate Shipping &amp; Taxes
                </label>
                <hr>
                <p class="cart-total right">
                    <strong>Sub-Total</strong>:	$100.00<br>
                    <strong>Eco Tax (-2.00)</strong>: $2.00<br>
                    <strong>VAT (17.5%)</strong>: $17.50<br>
                    <strong>Total</strong>: ${{cart.get_total_price}}<br>
                </p>
                <hr/>
                <p class="buttons center">				
                    <button class="btn" type="button">Update</button>
                    <button class="btn" type="button">Continue</button>
                    
                </p>
                <a href="{% url 'order:checkout' %}">checkout</a>					
            </div>
            <div class="span3 col">
                <div class="block">	
                    <ul class="nav nav-list">
                        <li class="nav-header">SUB CATEGORIES</li>
                        <li><a href="products.html">Nullam semper elementum</a></li>
                        <li class="active"><a href="products.html">Phasellus ultricies</a></li>
                        <li><a href="products.html">Donec laoreet dui</a></li>
                        <li><a href="products.html">Nullam semper elementum</a></li>
                        <li><a href="products.html">Phasellus ultricies</a></li>
                        <li><a href="products.html">Donec laoreet dui</a></li>
                    </ul>
                    <br/>
                    <ul class="nav nav-list below">
                        <li class="nav-header">MANUFACTURES</li>
                        <li><a href="products.html">Adidas</a></li>
                        <li><a href="products.html">Nike</a></li>
                        <li><a href="products.html">Dunlop</a></li>
                        <li><a href="products.html">Yamaha</a></li>
                    </ul>
                </div>
                <div class="block">
                    <h4 class="title">
                        <span class="pull-left"><span class="text">Randomize</span></span>
                        <span class="pull-right">
                            <a class="left button" href="#myCarousel" data-slide="prev"></a><a class="right button" href="#myCarousel" data-slide="next"></a>
                        </span>
                    </h4>
                    <div id="myCarousel" class="carousel slide">
                        <div class="carousel-inner">
                            <div class="active item">
                                <ul class="thumbnails listing-products">
                                    <li class="span3">
                                        <div class="product-box">
                                            <span class="sale_tag"></span>												
                                            <a href="product_detail.html"><img alt="" src="themes/images/ladies/2.jpg"></a><br/>
                                            <a href="product_detail.html" class="title">Fusce id molestie massa</a><br/>
                                            <a href="#" class="category">Suspendisse aliquet</a>
                                            <p class="price">$261</p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="item">
                                <ul class="thumbnails listing-products">
                                    <li class="span3">
                                        <div class="product-box">												
                                            <a href="product_detail.html"><img alt="" src="themes/images/ladies/4.jpg"></a><br/>
                                            <a href="product_detail.html" class="title">Tempor sem sodales</a><br/>
                                            <a href="#" class="category">Urna nec lectus mollis</a>
                                            <p class="price">$134</p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>						
            </div>
        </div>
    </section>	
{% endblock main-content %}