Customer/urls.py
from django.urls import path
from .views import registration, profile_form, userprofile, login_form, logout_form
app_name = 'Customer'
urlpatterns = [
    path('registration/', registration, name='registration'),
    path('login/', login_form, name='login'),
    path('logout', logout_form, name='logout'),
    path('profile', userprofile, name='profile'),
    path('profile_update/', profile_form, name='profile_update')
]

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('display/', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('Customer/', include('Customer.urls')),
    path('order/',include('order.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>/', views.category_list, name='category'),
    path('product_detail/<slug:slug>/', views.product_detail, name='product_detail'),
]

store/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    @staticmethod
    def get_all_category():
        return Category.objects.all()


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    price = models.FloatField()
    description = models.TextField()
    available = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    added_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail', args=[self.slug])

    @staticmethod
    def get_all_product():
        return Product.objects.filter(available=True)

    @staticmethod
    def get_one_product(slug):
        return Product.objects.filter(slug=slug)

    @staticmethod
    def get_all_featured_product():
        return Product.objects.filter(featured=True)

    @staticmethod
    def get_product_by_category_id(category_id):
        if category_id:
            return Product.objects.filter(category=category_id)
        else:
            return Product.objects.filter(available=True)

store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category
from cart.cart import Cart
from cart.forms import CartAddProductForm
# Create your views here.


def index(request):
    products = Product.get_all_product()
    featured_products = Product.get_all_featured_product()
    category = Category.get_all_category()
    return render(request, 'index.html', {'products': products, 'featured_products': featured_products,
                                          'category': category})


def category_list(request, category_id):
    category = Category.get_all_category()
    products = Product.get_product_by_category_id(category_id)
    return render(request, 'category.html', {'products': products, 'category': category})


def product_detail(request, slug):
    category = Category.get_all_category()
    product = Product.get_one_product(slug)
    form = CartAddProductForm()
    return render(request, 'product_detail.html', {'product': product, 'category': category, 'form': form})

store/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Bootstrap E-commerce Templates</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<!--[if ie]><meta content='IE=8' http-equiv='X-UA-Compatible'/><![endif]-->
		<!-- bootstrap -->
		<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">      
		<link href="{% static 'bootstrap/css/bootstrap-responsive.min.css' %}" rel="stylesheet">
		
		<link href="{% static 'themes/css/bootstrappage.css' %}" rel="stylesheet"/>
		
		<!-- global styles -->
		<link href="{% static 'themes/css/flexslider.css' %}" rel="stylesheet"/>
		<link href="{% static 'themes/css/main.css' %}" rel="stylesheet"/>

		<!-- scripts -->
		<script src="{% static 'themes/js/jquery-1.7.2.min.js' %}"></script>
		<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>				
		<script src="{% static 'themes/js/superfish.js' %}"></script>	
		<script src="{% static 'themes/js/jquery.scrolltotop.js' %}"></script>
		<!--[if lt IE 9]>			
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
			<script src="js/respond.min.js"></script>
		<![endif]-->
	</head>
    <body>		
		<div id="top-bar" class="container">
			<div class="row">
				<div class="span4">
					<form method="POST" class="search_form">
						<input type="text" class="input-block-level search-query" Placeholder="eg. T-sirt">
					</form>
				</div>
				<div class="span8">
					<div class="account pull-right">
						<ul class="user-menu">				
							<li><a href="{% url 'Customer:profile' %}">My Account</a></li>
							<li><a href="{% url 'cart:cart_detail' %}">Your Cart</a></li>
							<li><a href="checkout.html">Checkout</a></li>		
							{% if user.is_authenticated %}
								<li><a href="{% url 'Customer:logout' %}">logout</a></li>	
							{% else %}
								<li><a href="{% url 'Customer:login' %}">Login</a></li>
								<li><a href="{% url 'Customer:registration' %}">signup</a></li>
							{% endif %}			
									
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div id="wrapper" class="container">
			{% block navbar %}
                
            {% endblock navbar %}


			{% block slider %}
                
            {% endblock slider %}


            {% block main-content %}
                
            {% endblock main-content %}
			<section class="our_client">
				<h4 class="title"><span class="text">Manufactures</span></h4>
				<div class="row">					
					<div class="span2">
						<a href="#"><img alt="" src="themes/images/clients/14.png"></a>
					</div>
					<div class="span2">
						<a href="#"><img alt="" src="themes/images/clients/35.png"></a>
					</div>
					<div class="span2">
						<a href="#"><img alt="" src="themes/images/clients/1.png"></a>
					</div>
					<div class="span2">
						<a href="#"><img alt="" src="themes/images/clients/2.png"></a>
					</div>
					<div class="span2">
						<a href="#"><img alt="" src="themes/images/clients/3.png"></a>
					</div>
					<div class="span2">
						<a href="#"><img alt="" src="themes/images/clients/4.png"></a>
					</div>
				</div>
			</section>
			<section id="footer-bar">
				<div class="row">
					<div class="span3">
						<h4>Navigation</h4>
						<ul class="nav">
							<li><a href="./index.html">Homepage</a></li>  
							<li><a href="./about.html">About Us</a></li>
							<li><a href="./contact.html">Contac Us</a></li>
							<li><a href="./cart.html">Your Cart</a></li>
							<li><a href="./register.html">Login</a></li>							
						</ul>					
					</div>
					<div class="span4">
						<h4>My Account</h4>
						<ul class="nav">
							<li><a href="#">My Account</a></li>
							<li><a href="#">Order History</a></li>
							<li><a href="#">Wish List</a></li>
							<li><a href="#">Newsletter</a></li>
						</ul>
					</div>
					<div class="span5">
						<p class="logo"><img src="themes/images/logo.png" class="site_logo" alt=""></p>
						<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. the  Lorem Ipsum has been the industry's standard dummy text ever since the you.</p>
						<br/>
						<span class="social_icons">
							<a class="facebook" href="#">Facebook</a>
							<a class="twitter" href="#">Twitter</a>
							<a class="skype" href="#">Skype</a>
							<a class="vimeo" href="#">Vimeo</a>
						</span>
					</div>					
				</div>	
			</section>
			<section id="copyright">
				<span>Copyright 2013 bootstrappage template  All right reserved.</span>
			</section>
		</div>
		<script src="{% static 'themes/js/common.js' %}"></script>
		<script src="{% static 'themes/js/jquery.flexslider-min.js' %}"></script>
		<script type="text/javascript">
			$(function() {
				$(document).ready(function() {
					$('.flexslider').flexslider({
						animation: "fade",
						slideshowSpeed: 4000,
						animationSpeed: 600,
						controlNav: false,
						directionNav: true,
						controlsContainer: ".flex-container" // the container that holds the flexslider
					});
				});
			});
		</script>
    </body>
</html>

store/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}
<section class="navbar main-menu">
    <div class="navbar-inner main-menu">				
        <a href="{% url 'index' %}" class="logo pull-left"><img src="{% static 'themes/images/logo.png' %}" class="site_logo" alt=""></a>
        <nav id="menu" class="pull-right">
            <ul>
               {% for category in category %}
                <li><a href="{% url 'category' category.id %}">{{category.name}}</a></li>
                {% endfor %}
            </ul>
        </nav>
    </div>
</section>
{% endblock navbar %}

{% block main-content %}
<section class="main-content">				
    <div class="row">						
        <div class="span9">								
            <ul class="thumbnails listing-products">
                {% for product in products %}
                <li class="span3">
                    <div class="product-box">
                        <span class="sale_tag"></span>
                        <p><a href="{{product.get_absolute_url}}"><img src="{{product.image.url}}" alt="" /></a></p>
                        <a href="product_detail.html" class="title">{{product.name}}</a><br/>
                        <a href="products.html" class="category">{{product.category}}</a>
                        <p class="price">${{product.price}}</p>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock main-content %}

store/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}
<section class="navbar main-menu">
    <div class="navbar-inner main-menu">				
        <a href="{% url 'index' %}" class="logo pull-left"><img src="{% static 'themes/images/logo.png' %}" class="site_logo" alt=""></a>
        <nav id="menu" class="pull-right">
            <ul>
                {% for category in category %}
                <li><a href="{% url 'category' category.id %}">{{category.name}}</a></li>
                {% endfor %}
            </ul>
        </nav>
    </div>
</section>
{% endblock navbar %}

{% block slider %}
<section  class="homepage-slider" id="home-slider">
    <div class="flexslider">
        <ul class="slides">
            <li>
                <img src="themes/images/carousel/banner-1.jpg" alt="" />
            </li>
            <li>
                <img src="themes/images/carousel/banner-2.jpg" alt="" />
                <div class="intro">
                    <h1>Mid season sale</h1>
                    <p><span>Up to 50% Off</span></p>
                    <p><span>On selected items online and in stores</span></p>
                </div>
            </li>
        </ul>
    </div>			
</section>
{% endblock slider %}

{% block main-content %}
<section class="main-content">
    <div class="row">
        <div class="span12">													
            <div class="row">
                <div class="span12">
                    <h4 class="title">
                        <span class="pull-left"><span class="text"><span class="line">Feature <strong>Products</strong></span></span></span>
                        <span class="pull-right">
                            <a class="left button" href="#myCarousel" data-slide="prev"></a><a class="right button" href="#myCarousel" data-slide="next"></a>
                        </span>
                    </h4>
                    <div id="myCarousel" class="myCarousel carousel slide">
                        <div class="carousel-inner">
                            <div class="active item">
                                <ul class="thumbnails">	
                                    {% for feature in featured_products %}
                                    <li class="span3">
                                        <div class="product-box">
                                            <span class="sale_tag"></span>
                                            <p><a href="{{feature.get_absolute_url}}"><img src="{{feature.image.url}}" alt="" /></a></p>
                                            <a href="{{feature.get_absolute_url}}." class="title">{{feature.name}}</a><br/>
                                            <a href="{{feature.get_absolute_url}}" class="category">{{feature.category}}</a>
                                            <p class="price">{{feature.price}}</p>
                                        </div>
                                    </li> 			
                                    {% endfor %}											  																					
                                </ul>
                            </div>
                        </div>							
                    </div>
                </div>						
            </div>
            <br/>
            <div class="row">
                <div class="span12">
                    <h4 class="title">
                        <span class="pull-left"><span class="text"><span class="line">Latest <strong>Products</strong></span></span></span>
                        <span class="pull-right">
                            <a class="left button" href="#myCarousel-2" data-slide="prev"></a><a class="right button" href="#myCarousel-2" data-slide="next"></a>
                        </span>
                    </h4>
                    <div id="myCarousel-2" class="myCarousel carousel slide">
                        <div class="carousel-inner">
                            <div class="active item">
                                <ul class="thumbnails">	
                                    {% for product in products %}
                                    <li class="span3">
                                        <div class="product-box">
                                            <span class="sale_tag"></span>
                                            <p><a href="{{product.get_absolute_url}}"><img src="{{product.image.url}}" alt="" /></a></p>
                                            <a href="{{product.get_absolute_url}}" class="title">{{product.name}}</a><br/>
                                            <a href="{{product.get_absolute_url}}" class="category">{{product.category}}</a>
                                            <p class="price">${{product.price}}</p>
                                        </div>
                                    </li>
                                    {% endfor %}																						
                                </ul>
                            </div>
                        </div>							
                    </div>
                </div>						
            </div>
            <div class="row feature_box">						
                <div class="span4">
                    <div class="service">
                        <div class="responsive">	
                            <img src="themes/images/feature_img_2.png" alt="" />
                            <h4>MODERN <strong>DESIGN</strong></h4>
                            <p>Lorem Ipsum is simply dummy text of the printing and printing industry unknown printer.</p>									
                        </div>
                    </div>
                </div>
                <div class="span4">	
                    <div class="service">
                        <div class="customize">			
                            <img src="themes/images/feature_img_1.png" alt="" />
                            <h4>FREE <strong>SHIPPING</strong></h4>
                            <p>Lorem Ipsum is simply dummy text of the printing and printing industry unknown printer.</p>
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="service">
                        <div class="support">	
                            <img src="themes/images/feature_img_3.png" alt="" />
                            <h4>24/7 LIVE <strong>SUPPORT</strong></h4>
                            <p>Lorem Ipsum is simply dummy text of the printing and printing industry unknown printer.</p>
                        </div>
                    </div>
                </div>	
            </div>		
        </div>				
    </div>
</section>
{% endblock main-content %}

store/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}
<section class="navbar main-menu">
    <div class="navbar-inner main-menu">				
        <a href="{% url 'index' %}" class="logo pull-left"><img src="{% static 'themes/images/logo.png' %}" class="site_logo" alt=""></a>
        <nav id="menu" class="pull-right">
            <ul>
               {% for category in category %}
                <li><a href="{% url 'category' category.id %}">{{category.name}}</a></li>
                {% endfor %}
            </ul>
        </nav>
    </div>
</section>
{% endblock navbar %}
{% block main-content %}
<section class="main-content">				
    <div class="row">	
        {% for product in product %}				
        <div class="span9">
            <div class="row">
                <div class="span4">
                    <a href="themes/images/ladies/1.jpg" class="thumbnail" data-fancybox-group="group1" title="Description 1"><img alt="" src="{{product.image.url}}"></a>												
                    <ul class="thumbnails small">								
                        <li class="span1">
                            <a href="themes/images/ladies/2.jpg" class="thumbnail" data-fancybox-group="group1" title="Description 2"><img src="{{product.image.url}}" alt=""></a>
                        </li>								
                        <li class="span1">
                            <a href="themes/images/ladies/3.jpg" class="thumbnail" data-fancybox-group="group1" title="Description 3"><img src="{{product.image.url}}" alt=""></a>
                        </li>													
                        <li class="span1">
                            <a href="themes/images/ladies/4.jpg" class="thumbnail" data-fancybox-group="group1" title="Description 4"><img src="{{product.image.url}}" alt=""></a>
                        </li>
                        <li class="span1">
                            <a href="themes/images/ladies/5.jpg" class="thumbnail" data-fancybox-group="group1" title="Description 5"><img src="{{product.image.url}}" alt=""></a>
                        </li>
                    </ul>
                </div>
                <div class="span5">
                    <address>
                        <strong>Brand:</strong> <span>{{product.name}}</span><br>
                        <strong>Product Code:</strong> <span>Product 14</span><br>
                        <strong>Reward Points:</strong> <span>0</span><br>
                        <strong>Availability:</strong> <span>IN Stock</span><br>								
                    </address>									
                    <h4><strong>Price: ${{product.price}}</strong></h4>
                </div>
                <div class="span5">
                    <form class="form-inline">
                        <label class="checkbox">
                            <input type="checkbox" value=""> Option one is this and that
                        </label>
                        <br/>
                        <label class="checkbox">
                          <input type="checkbox" value=""> Be sure to include why it's great
                        </label>
                        <p>&nbsp;</p>
                    </form>
                    <form action="{% url 'cart:cart_add' product.id %}" method="POST" class="form-inline">
                        {% csrf_token %}
                        {{form}}
                        <button class="btn btn-inverse" type="submit">Add to cart</button>
                    </form>
                </div>							
            </div>
            <div class="row">
                <div class="span9">
                    <ul class="nav nav-tabs" id="myTab">
                        <li class="active"><a href="#home">Description</a></li>
                        <li class=""><a href="#profile">Additional Information</a></li>
                    </ul>							 
                    <div class="tab-content">
                        <div class="tab-pane active" id="home">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem</div>
                        <div class="tab-pane" id="profile">
                            <table class="table table-striped shop_attributes">	
                                <tbody>
                                    <tr class="">
                                        <th>Size</th>
                                        <td>Large, Medium, Small, X-Large</td>
                                    </tr>		
                                    <tr class="alt">
                                        <th>Colour</th>
                                        <td>Orange, Yellow</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>							
                </div>						
            </div>
        </div>
       
    </div>
    {% endfor %}	
</section>	
{% endblock main-content %}